using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using DietitianApp.Agent.Infrastructure.Persistence;
#nullable disable
namespace DietitianApp.Agent.Infrastructure.Migrations;
[Migration("20260714210000_InitialCreate")]
[DbContext(typeof(AgentDbContext))]
public partial class InitialCreate : Migration
{
 protected override void Up(MigrationBuilder m)
 {
  m.CreateTable(name:"MessageTemplates",columns:t=>new{Id=t.Column<Guid>(type:"TEXT",nullable:false),Name=t.Column<string>(type:"TEXT",maxLength:128,nullable:false),Content=t.Column<string>(type:"TEXT",maxLength:4096,nullable:false),IsActive=t.Column<bool>(type:"INTEGER",nullable:false),CreatedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:false),UpdatedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:false)},constraints:c=>c.PrimaryKey("PK_MessageTemplates",x=>x.Id));
  m.CreateTable(name:"SendBatches",columns:t=>new{Id=t.Column<Guid>(type:"TEXT",nullable:false),MessageContent=t.Column<string>(type:"TEXT",maxLength:4096,nullable:false),CreatedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:false),StartedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:true),CompletedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:true),Status=t.Column<int>(type:"INTEGER",nullable:false),TotalCount=t.Column<int>(type:"INTEGER",nullable:false),SuccessCount=t.Column<int>(type:"INTEGER",nullable:false),FailureCount=t.Column<int>(type:"INTEGER",nullable:false),CancelledCount=t.Column<int>(type:"INTEGER",nullable:false)},constraints:c=>c.PrimaryKey("PK_SendBatches",x=>x.Id));
  m.CreateTable(name:"WhatsAppGroups",columns:t=>new{Id=t.Column<Guid>(type:"TEXT",nullable:false),ExternalName=t.Column<string>(type:"TEXT",maxLength:256,nullable:false),DisplayName=t.Column<string>(type:"TEXT",maxLength:256,nullable:false),Prefix=t.Column<string>(type:"TEXT",nullable:true),IsActive=t.Column<bool>(type:"INTEGER",nullable:false),IsVerified=t.Column<bool>(type:"INTEGER",nullable:false),VerifiedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:true),CreatedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:false),UpdatedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:false)},constraints:c=>c.PrimaryKey("PK_WhatsAppGroups",x=>x.Id));
  m.CreateTable(name:"SendBatchItems",columns:t=>new{Id=t.Column<Guid>(type:"TEXT",nullable:false),SendBatchId=t.Column<Guid>(type:"TEXT",nullable:false),WhatsAppGroupId=t.Column<Guid>(type:"TEXT",nullable:false),GroupNameSnapshot=t.Column<string>(type:"TEXT",maxLength:256,nullable:false),Status=t.Column<int>(type:"INTEGER",nullable:false),AttemptCount=t.Column<int>(type:"INTEGER",nullable:false),StartedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:true),CompletedAtUtc=t.Column<DateTimeOffset>(type:"TEXT",nullable:true),ErrorCode=t.Column<string>(type:"TEXT",nullable:true),ErrorMessage=t.Column<string>(type:"TEXT",nullable:true),ScreenshotPath=t.Column<string>(type:"TEXT",nullable:true),TracePath=t.Column<string>(type:"TEXT",nullable:true)},constraints:c=>{c.PrimaryKey("PK_SendBatchItems",x=>x.Id);c.ForeignKey(name:"FK_SendBatchItems_SendBatches_SendBatchId",column:x=>x.SendBatchId,principalTable:"SendBatches",principalColumn:"Id",onDelete:ReferentialAction.Cascade);c.ForeignKey(name:"FK_SendBatchItems_WhatsAppGroups_WhatsAppGroupId",column:x=>x.WhatsAppGroupId,principalTable:"WhatsAppGroups",principalColumn:"Id",onDelete:ReferentialAction.Restrict);});
  m.CreateIndex(name:"IX_MessageTemplates_Name",table:"MessageTemplates",column:"Name",unique:true);m.CreateIndex(name:"IX_WhatsAppGroups_ExternalName",table:"WhatsAppGroups",column:"ExternalName",unique:true);m.CreateIndex(name:"IX_SendBatchItems_SendBatchId",table:"SendBatchItems",column:"SendBatchId");m.CreateIndex(name:"IX_SendBatchItems_WhatsAppGroupId",table:"SendBatchItems",column:"WhatsAppGroupId");
 }
 protected override void Down(MigrationBuilder m){m.DropTable(name:"MessageTemplates");m.DropTable(name:"SendBatchItems");m.DropTable(name:"SendBatches");m.DropTable(name:"WhatsAppGroups");}
}
